feat: 166 expose Stanza React components
StanzaSystems/stanza-js pull request #167
Opened 2023-09-14 15:31 UTC by ktrz-sre-is

* implement WithStanzaContextName
* implement WithStanzaFeature
* update sample apps

resolves #166

2023-09-14 17:24 UTC, jamie-kuppens-sre-is requested changes

2023-09-14 17:24 UTC, jamie-kuppens-sre-is commented on packages/stanza-react/src/context/WithStanzaContextName.tsx
> +}
Question: I don't know if I understand the purpose of this component. Is this to make it so you cannot pass a name to the context that is undefined? I'm wondering if this can be avoided and `<StanzaContextName.Provider>` can be used directly by removing undefined from the context type signature and setting a default.

My understanding is that `value` has to be passed to the provider and cannot be omitted even if `undefined` is in the signature, so I doubt the default value would ever be used anyways. I'll be honest though the Context API for React confuses me 😅 I got lost in a couple of GitHub threads about `defaultValue` with Context and it just confused me more.

2023-09-14 17:24 UTC, jamie-kuppens-sre-is commented on packages/stanza-react/src/context/StanzaContextName.ts
> +export const StanzaContextName = createContext<string | undefined>(undefined)
Question: Is there harm in setting a default value here?

2023-09-14 17:24 UTC, jamie-kuppens-sre-is commented on packages/stanza-react/src/feature/WithStanzaFeature.tsx
> +    : renderFallback({ message })
I assume we're changing this later right? If so this is fine.

2023-09-14 17:24 UTC, jamie-kuppens-sre-is commented on packages/stanza-react/src/hooks/useStanzaContext.ts
> +  const [state, setState] = useState<StanzaContext | undefined>(undefined)
We don't have to explicitly pass undefined in this case:

```suggestion
  const [state, setState] = useState<StanzaContext | undefined>()
```

2023-09-15 06:22 UTC, ktrz-sre-is commented on packages/stanza-react/src/context/WithStanzaContextName.tsx
> +}
The purpose of this component is so that the developers do not use the Context API directly. Additionally, I need the default value to be `undefined` so I can detect that no context has been provided for a given `WithStanzaFeature` component to throw an appropriate error

2023-09-15 06:22 UTC, ktrz-sre-is commented on packages/stanza-react/src/context/StanzaContextName.ts
> +export const StanzaContextName = createContext<string | undefined>(undefined)
I need `undefined` to be able to detect that context name has not been set

2023-09-15 06:26 UTC, ktrz-sre-is commented on packages/stanza-react/src/feature/WithStanzaFeature.tsx
> +    : renderFallback({ message })
I wasn't planning to need to change this code
We only get ActionCode from the API and not a feature state. I assumed that the ActionCode would end up with `ENABLED` and `DISABLED` values. So that's why I've done a conditional logic on the `ActionCode.ENABLED` as I don't expect it to change.

2023-09-15 06:27 UTC, ktrz-sre-is commented on packages/stanza-react/src/hooks/useStanzaContext.ts
> +  const [state, setState] = useState<StanzaContext | undefined>(undefined)
done

2023-09-15 07:47 UTC, ktrz-sre-is commented on packages/stanza-react/src/feature/WithStanzaFeature.tsx
> +    : renderFallback({ message })
Ah... after looking at your PRs for removing action codes I think I need to adjust the browser SDK as well

2023-09-15 16:29 UTC, jamie-kuppens-sre-is approved these changes
Alright I think this looks good 👍 We should probably coordinate with the team to figure out how to roll this out with other action code changes.

2023-09-18 07:45 UTC, merged