feat: improve express-demo docs
StanzaSystems/stanza-js pull request #188
Opened 2023-10-26 14:46 UTC by sre-is-carlos

2023-10-26 14:51 UTC, ktrz-sre-is requested changes

2023-10-26 14:51 UTC, ktrz-sre-is commented on samples/express-demo/README.md
> +2. Set the `STANZA_HUB_ADDRESS` to your environment, and don't forget to add the port on it (e.g.: `https://hub.dev.getstanza.dev:9020`).
we should not mention the dev instance of hub in the docs. This doc is meant for outside users

2023-10-26 14:51 UTC, ktrz-sre-is commented on samples/express-demo/README.md
> +3. In the `.env` file, set `STANZA_API_KEY` to a [API key](https://ui.demo.getstanza.io/admin?tab=keys) for your local environment.
please change references from demo to prod links

2023-10-26 14:51 UTC, ktrz-sre-is commented on samples/express-demo/README.md
> +2. Set the `STANZA_HUB_ADDRESS` to your environment, and don't forget to add the port on it (e.g.: `https://hub.dev.getstanza.dev:9020`).
please modify `.env.sample` to contain the port

2023-10-26 14:51 UTC, ktrz-sre-is commented on samples/express-demo/README.md
> +5. Create a service named `expressDemo` and set `STANZA_SERVICE_NAME=expressDemo` in the `.env` file.
please change the `.env.sample` to contain `expressDemo` instead of `express-demo` and then you can skip the ```and set `STANZA_SERVICE_NAME=expressDemo` in the `.env` file. ``` part

2023-10-26 14:51 UTC, ktrz-sre-is commented on samples/express-demo/README.md
> +6. In the [Stanza UI](https://ui.demo.getstanza.io/guards), create a guard:
please point to prod

2023-10-27 12:34 UTC, ktrz-sre-is commented on samples/express-demo/.env.example
> +STANZA_HUB_ADDRESS=https://hub.dev.getstanza.dev:9020
this should still point to production hub

2023-10-27 21:56 UTC, jamie-kuppens-sre-is approved these changes

2023-10-30 15:30 UTC, ktrz-sre-is approved these changes

2023-10-30 16:19 UTC, merged