feat: add client id to getserviceconfig call
StanzaSystems/stanza-js pull request #189
Opened 2023-10-26 20:19 UTC by sre-is-carlos

2023-10-27 16:57 UTC, sre-is-carlos commented on packages/node/src/hub/rest/createRestHubService.ts
> +    fetchServiceConfig: async (options) => {
Here, I changed the pattern to equal the 'grpc.'

2023-10-27 22:09 UTC, jamie-kuppens-sre-is approved these changes

2023-10-27 22:10 UTC, jamie-kuppens-sre-is commented
I think this looks good but I'm curious what Chris thingks. @ktrz-sre-is Does this look good to you?

2023-10-30 09:58 UTC, ktrz-sre-is requested changes
This looks good. But I think we need to modify `packages/node/src/service/startPollingConfigService.ts` to pass the `clientId` param down. Otherwise the client id is never going to be passed to the Hub Service

And maybe add some additional tests in `packages/node/src/service/fetchServiceConfig.test.ts`

2023-10-30 09:58 UTC, ktrz-sre-is commented on packages/node/src/hub/rest/createRestHubService.ts
> +    fetchServiceConfig: async (options) => {
👍

2023-10-31 07:16 UTC, ktrz-sre-is reviewed
Hey Carlos
I've added a couple of additional comments. If you have any questions I'd be happy to help

2023-10-31 07:16 UTC, ktrz-sre-is commented on packages/node/src/hub/api/serviceConfigResponse.ts
> +  clientId: z.string().optional(),
This ZOD validation is modeling the response from the hub.  We just send a client id as a request param and it does not contain the client id in the response

2023-10-31 07:16 UTC, ktrz-sre-is commented on packages/node/src/hub/model.ts
> +export type ServiceConfig = Pick<DataSent<ServiceConfigResponse>, 'version' | 'config' | 'clientId'>
same as above. The `clientId` is not going to be present in the ServiceConfig response

2023-10-31 07:16 UTC, ktrz-sre-is commented on packages/node/src/hub/model.ts
> +export type ServiceConfig = Pick<DataSent<ServiceConfigResponse>, 'version' | 'config' | 'clientId'>
I think just removing this should be enough as you didn't actually use it anywhere. We generate the client id in `initOrThrow` function and pass it down wherever it's needed

2023-10-31 07:16 UTC, ktrz-sre-is commented on packages/node/src/service/fetchServiceConfig.test.ts
> +  clientId: 'client-id',
this seems unnecessary as hub doesn't return client id back

2023-10-31 07:16 UTC, ktrz-sre-is commented on packages/node/src/hub/api/serviceConfigResponse.ts
> +  clientId: z.string().optional(),
Hub schema for reference https://github.com/StanzaSystems/apis/blob/main/openapiv2/hub.swagger.json#L801-L813

2023-10-31 07:16 UTC, ktrz-sre-is commented on packages/node/src/service/startPollingConfigService.ts
> +export const startPollingServiceConfig = (clientId?: string) => {
I think we can safely make in non optional as we always generate a client id

2023-10-31 15:29 UTC, ktrz-sre-is approved these changes
LGTM 🚢

2023-10-31 17:12 UTC, merged