refactor: code improvement changes
StanzaSystems/stanza-js pull request #197
Opened 2023-11-06 21:40 UTC by sre-is-carlos

Still waiting for the new Stripe key to have products registered for more tests.

It has added a new Stripe secret key to [Vercel](https://vercel.com/stanza/stanza-js-next-with-stripe/settings/environment-variables) variables.

2023-11-07 08:56 UTC, ktrz-sre-is commented on samples/next-with-stripe/components/ClearCart.tsx
> +  }, [clearCart])
If we are returning the `clearCart` as is then what is the purpose of this `useCallback`?

2023-11-07 08:56 UTC, ktrz-sre-is commented on samples/next-with-stripe/components/ElementsForm.tsx
> +    async function submit () {
I think we can extract this `submit` function out of the `handleSubmit` scope

2023-11-07 08:56 UTC, ktrz-sre-is commented on samples/next-with-stripe/components/ElementsForm.tsx
> +    void submit()
I've had this pattern bite me couple of times as it ignores possible errors. I would suggest
```suggestion
    submit().catch(() => {})
```
which passes linting as well but is safer

2023-11-07 08:56 UTC, ktrz-sre-is commented on samples/next-with-stripe/pages/checkout.tsx
> +  console.log(props)
can we remove the unnecessary console.log?

2023-11-07 08:56 UTC, ktrz-sre-is commented on samples/next-with-stripe/pages/checkout.tsx
> +    console.log(result.client_secret)
can we remove the unnecessary console.log?

2023-11-07 08:56 UTC, ktrz-sre-is commented on samples/next-with-stripe/pages/checkout.tsx
> +    const response = await fetch('http://localhost:4200/api/payment_intents', {
I think hardcoding `localhost:4200` will break when we try to deploy it on Vercel

2023-11-07 13:00 UTC, sre-is-carlos commented on samples/next-with-stripe/components/ClearCart.tsx
> +  }, [clearCart])
I'm using the useCallback to prevent the current state from getting stuck in a re-render infinite loop after finalizing the payment flow.

![Screenshot 2023-11-07 at 09 35 44](https://github.com/StanzaSystems/stanza-js/assets/147428731/5cd0377a-b68d-4905-a4e3-236977221532)

2023-11-07 13:25 UTC, ktrz-sre-is commented on samples/next-with-stripe/components/ClearCart.tsx
> +  }, [clearCart])
Ok, I understand the intention. But with your change it doesn't actually clear the cart anymore
![Screenshot 2023-11-07 at 14 22 59](https://github.com/StanzaSystems/stanza-js/assets/125868670/a71086e0-51c0-4063-83e2-47123361e470)
![Screenshot 2023-11-07 at 14 23 05](https://github.com/StanzaSystems/stanza-js/assets/125868670/575be2e1-a0a4-43c0-a66e-92ddc4773c49)

I think the solution would be to make the dependency array of `useEffect` empty and then you can get rid of the useCallback

2023-11-07 13:46 UTC, sre-is-carlos commented on samples/next-with-stripe/components/ClearCart.tsx
> +  }, [clearCart])
Oh, my bad 😅; let me use your suggestion.

2023-11-07 13:57 UTC, sre-is-carlos commented on samples/next-with-stripe/components/ElementsForm.tsx
> +const PaymentStatus = (props: PaymentStatusProps) => {
This was extracted from the ElementsForm component due to this SonarLint warning: "Do not define components during render".

2023-11-07 13:57 UTC, sre-is-carlos commented on samples/next-with-stripe/pages/checkout.tsx
> +const Checkout = (props: CheckoutProps) => {
This was created just to make use of the ElementsForm (and Stripe Elements) component.

2023-11-07 18:48 UTC, sre-is-carlos commented on samples/next-with-stripe/components/ClearCart.tsx
> +  }, [clearCart])
I just noticed that it doesn't work.

From what I tested `clearCart` [is an async function](https://projectinnocuous.slack.com/archives/C03SHR2EK61/p1699382496441629).

2023-11-07 21:00 UTC, sre-is-carlos commented on samples/next-with-stripe/components/CartSummary.tsx
> +          clearCart()
The previous implementation was passing the event to `clearCart`, and erroring on console.

2023-11-07 21:01 UTC, sre-is-carlos commented on samples/next-with-stripe/components/ClearCart.tsx
This was deleted because it is unnecessary now.

2023-11-07 21:05 UTC, sre-is-carlos commented on samples/next-with-stripe/pages/result.tsx
> +      clearCart()
We are now clearing the cart when the request has successfully finished; this implementation avoids the infinite loop we were having on `ClearCart` component.

2023-11-07 21:05 UTC, sre-is-carlos commented on samples/next-with-stripe/pages/result.tsx
> +      {hasClearedCart && <p>Cart cleared</p>}
We now depend on this state to show the cart cleared message.

2023-11-07 22:25 UTC, thanatusdev requested changes

2023-11-07 22:29 UTC, thanatusdev requested changes

2023-11-07 22:29 UTC, thanatusdev commented on samples/next-with-stripe/pages/result.tsx
> +  // eslint-disable-next-line react-hooks/exhaustive-deps
We should never disable the react rules. You can use useCallback or another hook to fix this issue.

2023-11-08 09:18 UTC, ktrz-sre-is commented on samples/next-with-stripe/pages/checkout.tsx
> +    console.log(error)
well, removing it can lead to render failing if fetch fails.

2023-11-08 13:44 UTC, sre-is-carlos commented on samples/next-with-stripe/pages/checkout.tsx
> +    console.log(error)
Which suggestion should I follow? 😅 

I first thought of reporting the error using Sentry or some other tooling, but it is not used in the demo.

2023-11-08 19:29 UTC, johnsre requested changes

2023-11-08 19:29 UTC, johnsre commented on samples/next-with-stripe/components/ElementsForm.tsx
> +    submit(e).catch(() => {})
You don't need to add a catch if you don't implement anything there.

2023-11-08 19:29 UTC, johnsre commented on samples/next-with-stripe/pages/checkout.tsx
> +    console.log(error)
Yeah, you can report it on sentry or create a boundary component.

2023-11-08 19:29 UTC, johnsre commented on samples/next-with-stripe/pages/index.tsx
> +    alert('Thank you for buying with us')
Are we using alerts on other parts of this project? Maybe we can implement a toast component or something better.

2023-11-08 19:35 UTC, sre-is-carlos commented on samples/next-with-stripe/components/ElementsForm.tsx
> +    submit(e).catch(() => {})
It was a suggestion made by @ktrz-sre-is

2023-11-08 19:35 UTC, sre-is-carlos commented on samples/next-with-stripe/components/ElementsForm.tsx
> +    submit(e).catch(() => {})
It is just to bypass eslint.

2023-11-08 19:37 UTC, sre-is-carlos commented on samples/next-with-stripe/pages/index.tsx
> +    alert('Thank you for buying with us')
It is not in the scope for now.

What do you think @ktrz-sre-is

2023-11-08 19:37 UTC, ktrz-sre-is commented on samples/next-with-stripe/components/ElementsForm.tsx
> +    submit(e).catch(() => {})
You actually need a catch here. Otherwise, if the error isn't caught it will trigger the global unhandled rejection event which is not good.

2023-11-08 19:38 UTC, johnsre commented on samples/next-with-stripe/components/ElementsForm.tsx
> +    submit(e).catch(() => {})
In this case, I would use it to return an error to the user if the submit fails. Please take a look at the stanza-ui register form.

2023-11-08 19:38 UTC, ktrz-sre-is commented on samples/next-with-stripe/pages/checkout.tsx
> +    console.log(error)
This is just an example app and since there is no Sentry configured in the demo app I think console log is just fine

2023-11-08 19:41 UTC, ktrz-sre-is commented on samples/next-with-stripe/pages/index.tsx
> +    alert('Thank you for buying with us')
I think as a simple solution for now we can just add a green box at the top of the page with the "Thank you for buying with us" message

2023-11-08 19:42 UTC, sre-is-carlos commented on samples/next-with-stripe/pages/index.tsx
> +    alert('Thank you for buying with us')
I'll create a ticket to keep track of these improvements.

Sounds good? @thanatusdev & @ktrz-sre-is

2023-11-08 19:44 UTC, ktrz-sre-is commented on samples/next-with-stripe/pages/index.tsx
> +    alert('Thank you for buying with us')
👍

2023-11-08 19:44 UTC, ktrz-sre-is approved these changes

2023-11-08 20:29 UTC, johnsre approved these changes

2023-11-08 20:35 UTC, merged