Adding mobile and react-native sdk and an example project
StanzaSystems/stanza-js pull request #214
Opened 2023-11-23 14:56 UTC by johnsre

2023-12-04 12:00 UTC, ktrz-sre-is commented on packages/core/src/index.ts
> +  getFeatureStatesAsync,
As suggested above I think it would be alright to make all the existing functions async and not make a separate set of async only ones

2023-12-04 12:03 UTC, ktrz-sre-is commented on packages/mobile/package.json
> +  "version": "0.0.1-beta",
let's keep versions aligned. It makes releasing upgrades much easier
```suggestion
  "version": "0.0.7-beta",
```

2023-12-04 12:06 UTC, ktrz-sre-is commented on packages/mobile/project.json
> +      "executor": "@nx/jest:jest",
can we use vitest instead of jest to keep the testing framework consistent?

2023-12-04 12:06 UTC, ktrz-sre-is commented on packages/stanza-rn/project.json
> +  "targets": {
Did you use a generator to create this lib? I believe we're missing the build target so that we can build and release the library

2023-12-04 12:09 UTC, ktrz-sre-is commented on samples/react-native-simple/package.json
> +  "name": "react-native-simple",
for the samples we probably don't need a separate package.json file. We should keep all the deps in the root to keep them consistent for the whole monorepo

2023-12-05 18:58 UTC, johnsre commented on packages/mobile/project.json
> +  "targets": {
The mobile project is not an app or a project that can be built is only a library using another library. The only project that can be executed and built is the react-native-simple project.

2023-12-05 19:00 UTC, johnsre commented on samples/react-native-simple/package.json
> +  "name": "react-native-simple",
If I remove the package.json file, I cannot execute the project because the react-native build adds the dependencies to that file and then verifies if those dependencies are there.

2023-12-05 19:02 UTC, johnsre commented on packages/core/src/globals.ts
> +let localStateProvider: LocalStateProvider | AsyncLocalStateProvider;
We'll need to discuss that more because this change will affect many places. I sent you a message on Slack.

2023-12-05 19:03 UTC, johnsre commented on packages/mobile/package.json
> +  "version": "0.0.1-beta",
Okay, I'll check this out.

2023-12-05 19:03 UTC, johnsre commented on packages/mobile/project.json
> +      "executor": "@nx/jest:jest",
Okay, I'll try to make this change.

2023-12-05 19:03 UTC, johnsre commented on packages/stanza-rn/project.json
> +      "executor": "@nx/jest:jest",
Okay, I'll try to make this change.

2023-12-05 19:06 UTC, ktrz-sre-is commented on packages/mobile/project.json
> +  "targets": {
As far as I understand we want this library to be usable by other developers in their apps (similarly to `@getstanza/browser`). That means that we need to build this library to be able to release it to npm.

2023-12-06 15:38 UTC, johnsre commented on packages/stanza-rn/project.json
> +      "executor": "@nx/jest:jest",
I cannot use the vitest because of the async storage mock, it only has integration with jest. https://react-native-async-storage.github.io/async-storage/docs/advanced/jest/. If you know a way to use this mockup in vitest, it would help a lot.

2023-12-06 15:38 UTC, johnsre commented on packages/mobile/project.json
> +      "executor": "@nx/jest:jest",
I cannot use the vitest because of the async storage mock, it only has integration with jest. https://react-native-async-storage.github.io/async-storage/docs/advanced/jest/. If you know a way to use this mockup in vitest, it would help a lot.

2023-12-07 10:00 UTC, ktrz-sre-is requested changes

2023-12-09 01:52 UTC, johnsre commented on packages/core/src/getFeatureStates.ts
> +// export async function getFeatureStates(
Yep, I deleted it now.

2023-12-09 01:53 UTC, johnsre commented on packages/core/src/globals.ts
> +// export function init(
Yep, I deleted it now.

2023-12-09 01:53 UTC, johnsre commented on packages/core/src/getFeatureStatesHot.ts
> +// export async function getFeatureStatesHot(
Yep, I deleted it now.

2023-12-09 01:53 UTC, johnsre commented on packages/core/src/getFeatureStatesStale.ts
> +// export function getFeatureStatesStale(features: string[]): FeatureState[] {
Yep, I deleted it now.

2023-12-09 01:54 UTC, johnsre commented on packages/stanza-rn/package.json
> +  "license": "MIT",
Fixed it.

2023-12-09 01:54 UTC, johnsre commented on packages/mobile/package.json
> +  "license": "MIT",
Fixed it.

2023-12-09 01:57 UTC, johnsre commented on packages/mobile/src/lib/asyncStorage/asyncStorage.ts
> +import RNAsyncStorage from '@react-native-async-storage/async-storage';
Suggestion implemented.

2023-12-09 01:57 UTC, johnsre commented on packages/browser/src/index.ts
> +    }
Suggestion implemented.

2023-12-09 01:58 UTC, johnsre commented on packages/core/src/models/stanzaCoreConfig.ts
> +  isReactNative?: boolean;
Removed it.

2023-12-09 02:06 UTC, johnsre commented on packages/core/src/pollFeatureStateUpdates.test.ts
> +    await vi.advanceTimersByTimeAsync(500);
It asks me to add an argument. I'll leave it 500 ms less than that the test fails.

2023-12-09 02:06 UTC, johnsre commented on packages/core/src/pollFeatureStateUpdates.test.ts
> +    await vi.advanceTimersByTimeAsync(500);
It asks me to add an argument. I'll leave it 500 ms less than that the test fails.

2023-12-09 02:07 UTC, johnsre commented on packages/core/src/pollFeatureStateUpdates.test.ts
> -    expect(mockGetFeaturesStatesHot).toHaveBeenCalledOnce();
It asks me to add an argument. I'll leave it 500 ms less than that the test fails.

2023-12-09 02:11 UTC, johnsre commented on packages/core/src/globals.ts
> +  await getEnablementNumber();
Suggestion implemented.

2023-12-09 02:11 UTC, johnsre commented on packages/core/src/init.ts
> +// export const init = (
Removed it.

2023-12-09 02:11 UTC, johnsre commented on packages/core/src/init.ts
> +  // Provider is optional, if not provided, use in memory provider
Done.

2023-12-09 02:12 UTC, johnsre commented on packages/core/src/models/localStateProvider.ts
> +// export interface LocalStateProvider {
Done.

2023-12-09 02:12 UTC, johnsre commented on packages/core/src/startPollingFeatureStateUpdates.ts
> +  const featureStates = await provider.getAllFeatureStates();
Implemented it.

2023-12-09 02:16 UTC, johnsre commented on packages/core/src/utils/inMemoryAsyncLocalStateProvider.test.ts
> +import { type FeatureState } from '../models/featureState';
You're right. I just removed it.

2023-12-09 02:17 UTC, johnsre commented on packages/node/src/open-telemetry/sampler/StanzaConfiguredSampler.ts
> +  constructor(private readonly serviceConfig: ServiceConfig['config']) {
I got this error: 
![Screenshot 2023-12-08 at 23 09 55](https://github.com/StanzaSystems/stanza-js/assets/147433179/16a6a31c-4f0b-4d68-90fa-5bd2169ce166)

2023-12-09 02:18 UTC, johnsre commented on packages/node/tsconfig.json
> +  "compilerOptions": {
According to the GitHub issues from Typescript, there's a bug in the old target versions, and I could only see the error above by using the ESNext target version.

2023-12-09 02:20 UTC, johnsre commented on packages/node/tsconfig.json
> +  "compilerOptions": {
But, since the error above is already solved I can revert this code, and I just did it.

2023-12-09 02:21 UTC, johnsre commented on packages/stanza-react/src/createStanzaInstance.ts
> +  await StanzaBrowser.init(config);
I agree that it would simplify the usages, but I don't think that using `.catch(() => {});` will be a good solution for the async functions as well since we are not tracking any errors.

2023-12-09 02:23 UTC, johnsre commented on packages/node/src/open-telemetry/sampler/StanzaConfiguredSampler.ts
> +  constructor(private readonly serviceConfig: ServiceConfig['config']) {
So, I made this change to fix it and be able to pass all tests.

2023-12-11 18:31 UTC, johnsre commented on packages/stanza-react/src/createStanzaInstance.ts
> +  await StanzaBrowser.init(config);
Okay, as you wish. I'll implement that.

2023-12-22 18:58 UTC, JLucasCAmorim commented on packages/stanza-react/src/createStanzaInstance.ts
> +  await StanzaBrowser.init(config);
Suggestion was implemented, but the async couldn't be removed; Eslint didn't allow it.

2024-01-02 13:15 UTC, ktrz-sre-is commented on packages/stanza-react/src/createStanzaInstance.ts
> +  await StanzaBrowser.init(config);
ESLint probably didn't allow the removal of async keyword because the return type was still a promise (I forgot to change it to just StanzaInstance in my previous suggestion). If you revert the return type to just `StanzaInstance` then there are no lint issues (after reverting the usages changes as well like in `samples/next-with-stripe/components/WithStanza.tsx`)

```ts
export const createStanzaInstance = (config: StanzaConfig): StanzaInstance => {
  StanzaBrowser.init(config).catch((e) => {
    console.warn('Error while initializing @getstanza/browser', e);
  });

  return {
    contextChanges: StanzaBrowser.contextChanges,
    featureChanges: StanzaBrowser.featureChanges,
  };
};
```

2024-01-02 14:27 UTC, ktrz-sre-is requested changes

2024-01-02 14:27 UTC, ktrz-sre-is commented on packages/mobile/src/asyncStorage/asyncStorage.ts
> +  }
emitting a [Storage event](https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event) is a feature of local storage that I used to sync between multiple tabs. I don't think it's necessary in case of React Native Async Storage 🤔

2024-01-02 14:27 UTC, ktrz-sre-is commented on packages/mobile/src/asyncStorage/asyncStorageProvider.ts
> +      });
this piece of code was included in local storage state provider to fix data becoming out of sync when using multiple tabs. I believe this is a localStorage specific solution and is not necessary here (and it will cause double emits to `featureStateChangeEmitter` here)

2024-01-02 14:27 UTC, ktrz-sre-is commented on packages/stanza-react/src/createStanzaInstance.ts
> +  });
this doesn't have to be async as we are not awaiting anything
```suggestion
export const createStanzaInstance = (
  config: StanzaConfig
): StanzaInstance => {
  StanzaBrowser.init(config).catch((e) => {
    console.warn('Error while initializing @getstanza/browser', e);
  });
```

2024-01-02 14:27 UTC, ktrz-sre-is commented on packages/stanza-rn/src/hooks/useStanzaContext.ts
> +      }, refreshTime),
just curious, why do we need throttling in React Native SDK. Does it cause trouble in the app if we don't have it?

2024-01-02 14:27 UTC, ktrz-sre-is commented on packages/stanza-rn/src/hooks/useStanzaContext.ts
> +    };
`addChangeListener` already returns the function to unsubscribe from changes
```suggestion
    return contextChanges.addChangeListener(processChanges);
```

2024-01-02 14:27 UTC, ktrz-sre-is commented on samples/next-with-stripe/components/WithStanza.tsx
> -const stanzaInstance = createStanzaInstance(browserConfig);
still relevant

2024-01-02 17:22 UTC, johnsre commented on packages/stanza-rn/src/hooks/useStanzaContext.ts
> +      }, refreshTime),
We have had many updates. It may affect the app performance in a long way, so I added it. However, I removed it since we don't need the event emitter on async storage. Please let me know if you have any suggestions about it.

![Screenshot 2024-01-02 at 14 12 16](https://github.com/StanzaSystems/stanza-js/assets/147433179/b3fe41a0-ce8c-4cb6-86ed-af1fdebbf12c)

2024-01-02 17:23 UTC, johnsre commented on packages/mobile/src/asyncStorage/asyncStorageProvider.ts
> +      });
Removed it.

2024-01-02 17:23 UTC, johnsre commented on packages/core/src/pollFeatureStateUpdates.test.ts
> -    expect(mockGetFeaturesStatesHot).toHaveBeenCalledOnce();
Added it.

2024-01-02 17:23 UTC, johnsre commented on packages/core/src/__tests__/features.test.ts
> +        .filter(Boolean)
Suggestion Applied.

2024-01-02 17:24 UTC, johnsre commented on packages/mobile/src/asyncStorage/asyncStorage.ts
> +  }
Got it, events were removed.

2024-01-02 17:24 UTC, johnsre commented on packages/stanza-rn/src/hooks/useStanzaContext.ts
> +    };
Suggestion applied.

2024-01-03 09:20 UTC, ktrz-sre-is approved these changes
Left last 2 suggestions but approving to not block this anymore

2024-01-03 09:20 UTC, ktrz-sre-is commented on packages/core/src/pollFeatureStateUpdates.test.ts
> +    await vi.advanceTimersByTimeAsync(500);
```suggestion
    await vi.advanceTimersByTimeAsync(0);
```

2024-01-03 09:20 UTC, ktrz-sre-is commented on packages/core/src/pollFeatureStateUpdates.test.ts
> +    await vi.advanceTimersByTimeAsync(500);
```suggestion
    await vi.advanceTimersByTimeAsync(0);
```

2024-02-08 21:44 UTC, merged